site_name: Rea
nav:
    - Home: index.md
    - Usage: usage.md
    - API:
      - rea-c++:
        - json: c++/json.md
        - pipe: c++/pipe.md
        - pipeline: c++/pipeline.md
        - stream: c++/stream.md
        - transaction: c++/transaction.md
        - pipes:
          - pipeLocal: c++/pipeLocal.md
          - pipePartial: c++/pipePartial.md
          - pipeDelegate: c++/pipeDelegate.md
          - pipeBuffer: c++/pipeBuffer.md
          - pipeThrottle: c++/pipeThrottle.md
          - pipeParallel: c++/pipeParallel.md
      - rea-qml:
        - Pipeline: qml/pipelineQML.md
        - Pipe: qml/qmlPipe.md
      - frm:
        - imagePool: frm/imagePool.md
        - command: frm/command.md
        - qsgModel: frm/qsgModel.md
        - qsgBoard: frm/qsgBoard.md
        - qsgBoardPlugin: frm/qsgBoardPlugin.md
      - storage: 
        - stgData: storage/stgData.md
        - fsStorage0: storage/fsStorage0.md
      - tcpSocket:
          - protocal: socket/protocal.md
          - normalServer: socket/normalServer.md
          - normalClient: socket/normalClient.md
      - serial:
          - modbusMaster: serial/modbusMaster.md
      - gui:
          - basic:
              - edit: gui/basic/edit.md
              - check: gui/basic/check.md
              - spin: gui/basic/spin.md
              - combo: gui/basic/combo.md
              - track: gui/basic/track.md
              - radio: gui/basic/radio.md
              - autosize: gui/basic/autosize.md
              - linechart: gui/basic/linechart.md
              - dynamicQML: gui/basic/dynamicQML.md
              - search: gui/basic/search.md
              - sizable: gui/basic/sizable.md
              - histogram: gui/basic/histogram.md
              - thistogram: gui/basic/thistogram.md
              - dialog:
                  - msgdialog: gui/basic/msgdialog.md
                  - file: gui/basic/file.md
                  - colorSelect: gui/basic/colorSelect.md
              - container:
                  - twindow: gui/basic/twindow.md
                  - swipe: gui/basic/swipe.md
                  - gridder: gui/basic/gridder.md
                  - flip: gui/basic/flip.md
                  - nest: gui/basic/nest.md
          - component:
              - progress: gui/component/progress.md
              - log: gui/component/log.md
              - status: gui/component/status.md
              - navigation: gui/component/navigation.md
              - matrix: gui/component/matrix.md
              - list: gui/component/list.md
              - treeNodeView: gui/component/treeNodeView.md
    - About: about.md
theme: readthedocs